# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    kvk_scraper.facebook.app_id: '1501904470103235'
    kvk_scraper.facebook.secret: '3883169799197bf8bf191a12922a7d85'

services:
    facebook_user_provider:
        class: NFQ\UserBundle\Provider\FacebookUserProvider
        arguments: [@fos_user.user_manager, {facebook: facebook_id, google: google_id}]
