<?php

namespace NFQ\KVKScraperBundle\Entity;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\Query;

/**
 * FacebookEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookEventRepository extends \Doctrine\ORM\EntityRepository
{

    public function saveFacebookEvent($facebookEvent){
        $this->getEntityManager()->persist($facebookEvent);
        $this->getEntityManager()->flush();
    }

    public function getByFacebookId($facebookEventId){
        return $this->findOneBy(['facebookEventId' => $facebookEventId]);
    }

    public function exists($facebookEventId){

        return $this->getByFacebookId($facebookEventId) !== null;

    }

    public function getEventsByDate(){
        $qb = $this->createQueryBuilder('facebook_events');
        $result=$qb->where($qb->expr()->like('facebook_events.startTime',':time'))
            ->setParameter('time','%2015-11-26%')
            ->getQuery()
            ->getResult();

        return $result;
    }

}
