<?php

namespace NFQ\KVKScraperBundle\Entity;

/**
 * UserEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function isUserGoingToEvent($user_id, $event_id){
        return $this->findOneBy([
            'userId' => $user_id,
            'eventId' => $event_id
        ]) !== null;
    }

    public function goToEvent($user_id, $event_id){
        $userEvent = new UserEvent();
        $userEvent->setUserId($user_id);
        $userEvent->setEventId($event_id);
        $userEvent->setGoing(true);
        $this->getEntityManager()->persist($userEvent);
        $this->getEntityManager()->flush();
    }

    /**
     * @param $user_id
     * @param $event_id
     * @return array
     */
    public function deleteAttendedEvent($user_id, $event_id)
    {
        $qb = $this->createQueryBuilder('UserEvent');

        $result = $qb->delete()
            ->where('UserEvent.userId = :user_id')
            ->andWhere('UserEvent.eventId = :event_id')
            ->setParameter('user_id', $user_id)
            ->setParameter('event_id',$event_id)
            ->getQuery()
            ->getResult();

        return $result;
    }
}
